Emulate block and item display entities in 1.19.4->1.19.3
ViaVersion/ViaBackwards pull request #871
Opened 2024-08-17 19:44 UTC by FlorianMichael

This PR adds very basic handling for block and item displays. 

Item displays:
![2024-08-17_21 39 27](https://github.com/user-attachments/assets/157af6fa-cf2b-4059-a516-0909abe510a5)
(Implemented by setting the item as head armor on the invisible armor stand)

Block displays:
![2024-08-17_21 40 12](https://github.com/user-attachments/assets/052fdbd7-ced7-4b9c-9ccd-a8f104e6b89c)
(Implemented by spawning a falling block and attaching it as passenger onto the armor stand to prevent position/rotation tracking)

Supersedes https://github.com/ViaVersion/ViaBackwards/pull/538

2024-08-21 12:45 UTC, kennytv requested changes

2024-08-21 12:45 UTC, kennytv commented on common/src/main/java/com/viaversion/viabackwards/protocol/v1_19_4to1_19_3/storage/EntityTracker1_19_4.java
> +    private final IntSet generatedEntities = new IntArraySet(); // Track entities spawned to prevent duplicated entity ids
IntOpenHashSet, this can get a lot of entities

2024-08-21 12:45 UTC, kennytv commented on common/src/main/java/com/viaversion/viabackwards/protocol/v1_19_4to1_19_3/storage/EntityTracker1_19_4.java
> +        for (final Integer id : entities.keySet()) {
int

2024-08-21 12:45 UTC, kennytv commented on common/src/main/java/com/viaversion/viabackwards/protocol/v1_19_4to1_19_3/storage/EntityTracker1_19_4.java
> +        final TrackedEntity entity = entity(id);
also return if this is null

2024-08-22 20:15 UTC, kennytv commented
I don't actually see the falling block when summoning any block display

2024-08-31 13:14 UTC, kennytv submitted a review, later dismissed

2024-08-31 13:16 UTC, kennytv commented
Works when spawned in next to you, but not when you join the server with one present or go in and out of range

2024-10-31 19:58 UTC, FlorianMichael commented
This is also the case with a vanilla 1.19.4 (you just have to wait a few seconds until the entity data is sent), I can't reproduce any loading issues longer than that

2024-11-07 18:09 UTC, CertifiedGlowie approved these changes

2024-11-18 13:38 UTC, kennytv approved these changes

2024-11-18 13:38 UTC, merged